#Numpy Library : 배열을 다루는 도구

In [ ]:
import numpy as np

In [ ]:
# 1차원 배열 생성하기
넘파이_배열1 = np.array([1,2,3,4])
넘파이_배열1

array([1, 2, 3, 4])

In [ ]:
# 2차원 배열 생성하기
넘파이_배열2 = np.array([[1,2,3,4],[11,12,13,14]])
넘파이_배열2

array([[ 1,  2,  3,  4],
       [11, 12, 13, 14]])

In [ ]:
# 3차원 배열 생성하기
넘파이_배열3 = np.array([ [[1,2,3,4],[11,12,13,14]],
                   [[21,22,23,24],[31,32,33,34]] ])
넘파이_배열3

array([[[ 1,  2,  3,  4],
        [11, 12, 13, 14]],

       [[21, 22, 23, 24],
        [31, 32, 33, 34]]])

In [ ]:
# .shape로 배열의 모양 보기
print(넘파이_배열1.shape)
print(넘파이_배열2.shape)
print(넘파이_배열3.shape)

(4,)
(2, 4)
(2, 2, 4)


In [ ]:
v1=np.array([1,2,3,4])
print(v1)

[1 2 3 4]


In [ ]:
v1=np.arange(10)
print(v1)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
v2=np.arange(1,10,2, dtype=int)
v3=np.arange(3.5,10.5,2, dtype=float)
print(v2)
print(v3)

[1 3 5 7 9]
[3.5 5.5 7.5 9.5]


In [ ]:
v4=np.arange(1,10,2)**2
print(v4)

[ 1  9 25 49 81]


In [ ]:
v5=np.arange(1,10,2)**3
print(v5)

[  1  27 125 343 729]


In [ ]:
v1=np.arange(12)
print(v1)
v2=v1.reshape(2,6)
print(v2)
v3=v1.reshape(2,6, order='F')
print(v3)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[[ 0  2  4  6  8 10]
 [ 1  3  5  7  9 11]]


In [ ]:
v1=np.arange(1,5).reshape(2,2)
print(v1)
print(np.add(v1,v1))
print(np.subtract(v1,v1))
print(np.multiply(v1,v1))
print(np.dot(v1,v1))

[[1 2]
 [3 4]]
[[2 4]
 [6 8]]
[[0 0]
 [0 0]]
[[ 1  4]
 [ 9 16]]
[[ 7 10]
 [15 22]]


In [ ]:
v1=np.arange(12)
print(v1)
v2=v1.reshape(2,3,2)
v3=v1.reshape(2,3,2,order='F')
print(v2)
print(v3)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]
[[[ 0  6]
  [ 2  8]
  [ 4 10]]

 [[ 1  7]
  [ 3  9]
  [ 5 11]]]


In [ ]:
v3=np.arange(3.5, 10.5, 2, dtype=float)
print(v3)
v4=np.arange(1,5).reshape(2,2)
print(v4)

[3.5 5.5 7.5 9.5]
[[1 2]
 [3 4]]


In [ ]:
v1=np.arange(12)
print(v1)
v2=v1.reshape(2,3,2, order='F')
print(v2)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[[ 0  6]
  [ 2  8]
  [ 4 10]]

 [[ 1  7]
  [ 3  9]
  [ 5 11]]]


In [ ]:
v3=np.arange(3.5, 10.5, 2, dtype=float)
print(v3)
v4=np.arange(1,5).reshape(2,2)
print(v4)
print(np.amax(v3))
print(np.amin(v4))
print(v3.dtype)
print(v4.shape)

[3.5 5.5 7.5 9.5]
[[1 2]
 [3 4]]
9.5
1
float64
(2, 2)
